name: fabricator_gen
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  build: ">=2.0.0 <3.0.0"
  source_gen: ^1.2.7
  fabricator:
    path: ../fabricator
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

dev_dependencies:
  build_test: ^2.1.7
  build_runner: ">=2.0.0 <3.0.0"
  freezed: ^2.5.0
  json_serializable: ^6.7.1
